weights: runs/yolov4-p7-visdrone-2160/weights/best.pt
cfg: ./models/yolov4-p7.yaml
data: ./data/a2i2-of.yaml
hyp: data/hyp.finetune.yaml
epochs: 30
batch_size: 2
img_size:
- 1845
- 1845
rect: false
resume: get_last
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
name: yolov4-p7-visdrone-2160-a2i2-of-1845
device: 0,1
multi_scale: false
single_cls: false
adam: false
sync_bn: true
local_rank: 0
logdir: runs/
total_batch_size: 4
world_size: 2
global_rank: 0
