#
#     /\_____/\
#    /  o   o  \
#   ( ==  ^  == )
#    )         (
#   (           )
#  ( (  )   (  ) )
# (__(__)___(__)__)
#
[tool.poetry]
name          = "mon"
version       = "1.2.0"
description   = "MON covers a wide range of research topics in computer vision, machine learning, and deep learning."
license       = "MIT"
authors       = [
    "Long H. Pham <longpham3105@gmail.com>",
]
maintainers   = [
    "Long H. Pham <longpham3105@gmail.com>",
]
readme        = "README.md"
repository    = "https://github.com/phlong3105/one"
documentation = "https://github.com/phlong3105/one/docs"
keywords      = [
    "computer vision",
    "image processing",
    "deep learning",
    "research",
]
classifiers   = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3 :: Only",
]
packages = [
    { include="mon", from="src" },
]
include  = []
exclude  = []

[tool.poetry.dependencies]
python   = ">=3.10"

[tool.poetry.group.lib.dependencies]
"yolov8" = { path="src/lib/yolov8", develop=true }
"zid"    = { path="src/lib/zid",    develop=true }

[tool.poetry.group.supr]
optional = true

[tool.poetry.group.supr.dependencies]
"supr"   = { path="src/supr", develop=true }

[tool.poetry.group.ug2]
optional = true

[tool.poetry.group.ug2.dependencies]
"ug2"    = { path="src/ug2", develop=true }

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
