# - Add conda-forge channel
#   conda config --append channels conda-forge
#
# - Install:
#   conda env create -f environment.yml
#
# - Install cudatoolkit separately:
#   conda install cudatoolkit=11.3
#
# - Install PyTorch separately:
#   conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch -c conda-forge
#
# - Update:
#   conda env update --name one --file environment.yml
#
# - Update all pip packages:
#   pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
#

name: one

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  # Base Python
  - cython
  - filterpy
  - git
  - git-lfs
  - librsvg
  - libiconv
  - libprotobuf
  - markdown
  - multipledispatch
  - munch
  - mypy
  - ninja
  - numpy
  - pandas
  - python=3.9
  - pyupgrade
  - pyqt
  - pyyaml
  - requests
  - rich
  - scipy
  - scikit-learn
  - sortedcontainers
  - tqdm
  - validators
  - xmltodict

  # CUDA
  # - cudatoolkit=11.7
  # - cudatoolkit-dev=11.6
  # - cudnn
  - pynvml

  # Image
  - albumentations
  - ffmpeg-python
  - opencv
  - pillow
  - py-opencv

  # PyTorch
  - einops
  - onnx
  - onnxruntime
  - pytorch>=1.13.1
  # - pytorch-cuda=11.7
  - torchvision>=0.14.1
  - torchaudio>=0.13.1
  - pretrainedmodels
  - pycocotools
  - pytorch-lightning>=1.8.1
  - pytorch-model-summary
  - timm
  - torchmetrics

  # Plot
  - matplotlib
  - pydot
  - seaborn
  - tensorboard
  - wandb

  # Pip
  - pip
  - pip:
      - flopco-pytorch
      - label-studio
      # - mediapipe
      # - opencv-python
      # - opencv-contrib-python
      - pyiqa
      - ray
